name: CI/CD - CitaCheck Frontend Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Connect to Tailscale
        uses: tailscale/github-action@v4
        with:
          authkey: ${{ secrets.TAILSCALE_KEY }}
          version: latest

      - name: Debug Tailscale
        run: |
          tailscale ip -4
          tailscale status
          echo "Pinging VPS..."
          ping -c 4 ${{ secrets.VPS_HOST }} || true
          echo "Check port..."
          nc -vz ${{ secrets.SSH_HOST }} 22 || true


      - name: deploy be
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/user-c-3/fe-final-project-pbkk
            git stash
            git checkout main
            git pull --rebase origin main
            git status
            sudo docker-compose down -v
            sudo docker-compose up --build --detach
